# inherits settings from https://github.com/Manjaro-Sway/.github/blob/main/.github/settings.yml
_extends: .github
repository:
  homepage: "https://git.hya.sk/skia/swaysome.git"
# you can extend settings using https://probot.github.io/apps/settings/
